<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_Program_Leaderboards</name>
   <tag></tag>
   <elementGuidId>72f59ebf-f36f-44f5-b08f-122a9ebf87ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dpd-name</name>
      <type>Main</type>
      <value>dpd-program-leaderboards</value>
      <webElementGuid>0fd651b6-66f5-4119-a8bf-f32bb15f9383</webElementGuid>
   </webElementProperties>
</WebElementEntity>
