<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Organization_Level_Leaderboards</name>
   <tag></tag>
   <elementGuidId>ab76ecae-5366-489d-a855-7e3aab63b096</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>40e5d691-5867-403c-9248-904476483fa1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
