<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>list_collapse_help_index_3</name>
   <tag></tag>
   <elementGuidId>8206222c-789e-47a9-b1a8-e617ede07b4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'list-collapse-help' and @index = '3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>list-collapse-help</value>
      <webElementGuid>0e008b35-346c-4bbd-9bcc-22f21d468eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>45f2c247-69ec-4e62-b68a-f739587e551d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
