<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_Successfully_Open_My_Learning_Journey - Radio button Completed</name>
   <tag></tag>
   <elementGuidId>52408959-3b77-49a1-8c56-aed2ea3ef206</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='content-main']/div/div/div[2]/div/div/label[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.ant-radio-button-wrapper:nth-child(4)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c7b4b19e-271b-4ef1-96e0-2dd89db59083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-radio-button ant-radio-button-checked</value>
      <webElementGuid>134172f5-cbf4-4aa3-bcce-1ebdae1a5f4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-main&quot;)/div[1]/div[@class=&quot;ant-row ant-row-top css-1eo2d7c&quot;]/div[@class=&quot;ant-col ant-col-12 css-1eo2d7c&quot;]/div[1]/div[@class=&quot;ant-radio-group ant-radio-group-outline ant-radio-group-middle radio-button-my-learning-journey css-1eo2d7c&quot;]/label[@class=&quot;ant-radio-button-wrapper ant-radio-button-wrapper-checked css-1eo2d7c&quot;]/span[@class=&quot;ant-radio-button ant-radio-button-checked&quot;]</value>
      <webElementGuid>f3f99271-e267-4bc6-a88c-9ed1a9b98d9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content-main']/div/div/div[2]/div/div/label[2]/span</value>
      <webElementGuid>6b8c1dc5-ae21-497a-ac27-538977d72015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/following::span[1]</value>
      <webElementGuid>1cdfea89-ff6b-4253-bf8b-a2b801f7d1ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter'])[1]/following::span[5]</value>
      <webElementGuid>00bf26a5-87e5-4307-b70f-b8bee6b0087c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ongoing'])[1]/preceding::span[2]</value>
      <webElementGuid>bf19d33c-24b3-4327-a9e5-5e96c271881d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New'])[1]/preceding::span[6]</value>
      <webElementGuid>3673699f-1bb3-48c8-8841-a8afc29330f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/span</value>
      <webElementGuid>3ac35881-c825-4f27-a116-9340a9604928</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
