<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Back_To_Login_Forgot_Password</name>
   <tag></tag>
   <elementGuidId>a2e57646-4131-46de-9f14-1af27dd5c8af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@dpd-name = 'dpd-program-leaderboards']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>square-podium-1-leaderboards</value>
      <webElementGuid>35998095-ccf4-458d-9043-40a3d2505f70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>podium</value>
      <webElementGuid>5773d428-81ef-4ddd-b89e-c9e7eb678536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dpd-name</name>
      <type>Main</type>
      <value>dpd-program-leaderboards</value>
      <webElementGuid>ae0db8ca-78f5-4a03-b1f5-a5c3d7f42b71</webElementGuid>
   </webElementProperties>
</WebElementEntity>
