<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>list_collapse_help_index_11</name>
   <tag></tag>
   <elementGuidId>fcd66f40-b537-4060-a5b9-5ede59b26bf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'list-collapse-help' and @index = '11']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>list-collapse-help</value>
      <webElementGuid>c03cb87f-1caa-44db-8e20-cffed4fb8401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>c79e5d52-a024-4070-9be9-17361fc6fae5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
