<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>list_collapse_help_index_12</name>
   <tag></tag>
   <elementGuidId>816384db-a898-441b-b8d3-7d69e53a4cde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'list-collapse-help' and @index = '12']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>list-collapse-help</value>
      <webElementGuid>16bef971-2935-4e96-abe9-54df5dc1f465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>7190c385-78a3-474a-bf66-b25fff08cbd8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
