<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>list_collapse_help_Index_0</name>
   <tag></tag>
   <elementGuidId>9f6cd57a-86bc-4e30-b744-b5d879f33f0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'list-collapse-help' and @index = '0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>list-collapse-help</value>
      <webElementGuid>c0c385df-1edf-4805-b7e7-9e2643e91fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>640d68fe-f0af-48c0-9d9d-6e65e16f53fe</webElementGuid>
   </webElementProperties>
</WebElementEntity>
