<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Name_Profile_Team_Monitoring</name>
   <tag></tag>
   <elementGuidId>10c94aba-eb6c-4558-8c37-ccbf74c318c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[name=&quot;btn-detailprofile-team-monitoring&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@name='btn-detailprofile-team-monitoring']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0874934a-bcfd-4846-bd86-a06b6401dee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn-detailprofile-team-monitoring</value>
      <webElementGuid>e0358ac9-e2aa-4b4e-b9e9-5900b8e164ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-link-detailprofile-team-monitoring</value>
      <webElementGuid>29c625fc-6b1d-4d5a-b39f-da1af09a9562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/team-monitoring/member/profile/32075</value>
      <webElementGuid>445d825f-f12d-425c-afd1-541a40e8a49c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Muhammad Hafizh Abdillah</value>
      <webElementGuid>4cf67afd-4864-4abe-8864-72e10754ea5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-main&quot;)/div[1]/div[@class=&quot;ant-row h-100 css-1eeazh9&quot;]/div[@class=&quot;ant-col ant-col-24 h-100 css-1eeazh9&quot;]/div[@class=&quot;ant-row css-1eeazh9&quot;]/div[@class=&quot;ant-card ant-card-bordered card-teamlearningstatusdetail-table-teammonitoring css-ngmjqf&quot;]/div[@class=&quot;ant-card-body&quot;]/div[@class=&quot;ant-row css-ngmjqf&quot;]/div[@class=&quot;ant-col ant-col-24 css-ngmjqf&quot;]/div[@class=&quot;ant-table-wrapper table-teamprofile-teammonitoring css-ngmjqf&quot;]/div[@class=&quot;ant-spin-nested-loading css-ngmjqf&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[@class=&quot;ant-table&quot;]/div[@class=&quot;ant-table-container&quot;]/div[@class=&quot;ant-table-content&quot;]/table[1]/tbody[@class=&quot;ant-table-tbody&quot;]/tr[@class=&quot;ant-table-row ant-table-row-level-0&quot;]/td[@class=&quot;ant-table-cell ant-table-cell-row-hover&quot;]/a[@class=&quot;btn-link-detailprofile-team-monitoring&quot;]</value>
      <webElementGuid>680035ce-5d31-4b4c-a97b-7071f42275f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@name='btn-detailprofile-team-monitoring']</value>
      <webElementGuid>189acb0a-71bd-4aca-98ee-a645047b534e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content-main']/div/div/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div/table/tbody/tr/td[2]/a</value>
      <webElementGuid>25e2d028-a5ef-4b4d-a8bc-6ef9aa4545da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Muhammad Hafizh Abdillah')]</value>
      <webElementGuid>f63cc566-ae48-4fc1-bece-6ecd6e07f223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role'])[1]/following::a[1]</value>
      <webElementGuid>0d547675-4002-4439-bd06-d2ca7a4809b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ongoing Program'])[1]/following::a[1]</value>
      <webElementGuid>8534ef57-e933-4fca-85ee-62ee15cf5174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::a[1]</value>
      <webElementGuid>d1d8f561-11b4-4ee7-96b4-4d302bce68d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Team Profile'])[2]/preceding::a[1]</value>
      <webElementGuid>24289b10-68e3-4e48-9bde-812f3ef8da98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/team-monitoring/member/profile/32075')]</value>
      <webElementGuid>50cdd58c-167d-4672-add3-2cd00cec7bcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>99cb29b5-c866-48d6-a146-820a465411f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@name = 'btn-detailprofile-team-monitoring' and @href = '/team-monitoring/member/profile/32075' and (text() = 'Muhammad Hafizh Abdillah' or . = 'Muhammad Hafizh Abdillah')]</value>
      <webElementGuid>eba3556c-329b-4bca-8ac3-414ed3f72eab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
