<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Send_Notification_Member_Team_Monitoring</name>
   <tag></tag>
   <elementGuidId>8c639e87-ba90-4790-a949-3f60561f0f54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;btn-send-notification-member-team-monitoring&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='btn-send-notification-member-team-monitoring']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ce328f32-fd72-482d-8ac7-a554c96b0620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn-send-notification-member-team-monitoring</value>
      <webElementGuid>fba652aa-92b6-49ed-a371-c90a7634ef0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f19539e1-9ac9-4e45-97d0-b19be185f9de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn css-1eeazh9 ant-btn-default btn-showdetaillearningstatus-teammonitoring false</value>
      <webElementGuid>a813a92c-b893-4769-9e7d-fc83e6247547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Send Notification</value>
      <webElementGuid>adfdea43-5240-48aa-9ea0-76b3488fa859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-main&quot;)/div[1]/div[@class=&quot;ant-row h-100 css-1eeazh9&quot;]/div[@class=&quot;ant-col ant-col-24 h-100 css-1eeazh9&quot;]/div[@class=&quot;ant-row css-1eeazh9&quot;]/div[@class=&quot;ant-card ant-card-bordered card-selectedprogram-table-teammonitoring css-1eeazh9&quot;]/div[@class=&quot;ant-card-body&quot;]/div[@class=&quot;ant-row css-1eeazh9&quot;]/div[@class=&quot;ant-col ant-col-12 css-1eeazh9&quot;]/button[@class=&quot;ant-btn css-1eeazh9 ant-btn-default btn-showdetaillearningstatus-teammonitoring false&quot;]</value>
      <webElementGuid>f925ceef-9e62-4fb1-bc2c-508e1e4d6424</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='btn-send-notification-member-team-monitoring']</value>
      <webElementGuid>174ce9bf-31e1-4571-914b-189e70e9e306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content-main']/div/div/div/div[2]/div/div/div/div/button</value>
      <webElementGuid>3f7b7ceb-ee9b-46d1-aa46-e68cb91d0b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show Team Profile'])[1]/following::button[1]</value>
      <webElementGuid>5f63db32-8f7b-4398-ac85-2447ffcb330b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Progress'])[1]/preceding::button[1]</value>
      <webElementGuid>28a483a9-e6cd-4bb2-84f5-df911b83b701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/button</value>
      <webElementGuid>f5eb9560-50e2-4ee1-954d-13ecff9e7dec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'btn-send-notification-member-team-monitoring' and @type = 'button' and (text() = 'Send Notification' or . = 'Send Notification')]</value>
      <webElementGuid>00fdca86-beff-48e6-8eb6-7444187803df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
