<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Cart_View_Team_Monitoring</name>
   <tag></tag>
   <elementGuidId>2a124429-f5ee-44d4-8f51-316c5e3d84e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>38</value>
      <webElementGuid>8efc5b83-87e1-467e-88ff-ba05d5576962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn-view-ongoing-team-team-monitoring</value>
      <webElementGuid>60b434fb-a63b-44e3-8d84-ec9b2425e3ae</webElementGuid>
   </webElementProperties>
</WebElementEntity>
