<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_Info_Team_Profile_Team_Monitoring</name>
   <tag></tag>
   <elementGuidId>61f25c13-6ae6-4111-97bd-f35497791323</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[name=&quot;icon-info-team-profile-team-monitoring&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@name='icon-info-team-profile-team-monitoring']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0700a5f8-db4f-48fa-9fd7-d048be28cf36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ic_info_teamprofile</value>
      <webElementGuid>930765b7-93a5-4b97-bac1-a24a2ca93d10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>icon-info-team-profile-team-monitoring</value>
      <webElementGuid>54739a61-53a5-413c-b51d-bf7290d52a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/ic_info_teamprofile-88f146be.svg</value>
      <webElementGuid>0db94da8-4fe2-4020-9e90-20773fcf4c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-main&quot;)/div[1]/div[@class=&quot;ant-row h-100 css-1eeazh9&quot;]/div[@class=&quot;ant-col ant-col-24 h-100 css-1eeazh9&quot;]/div[@class=&quot;ant-row css-1eeazh9&quot;]/div[@class=&quot;ant-card ant-card-bordered card-teamlearningstatusdetail-table-teammonitoring css-ngmjqf&quot;]/div[@class=&quot;ant-card-body&quot;]/div[@class=&quot;ant-row css-ngmjqf&quot;]/div[@class=&quot;ant-col ant-col-24 css-ngmjqf&quot;]/div[@class=&quot;ant-table-wrapper table-teamprofile-teammonitoring css-ngmjqf&quot;]/div[@class=&quot;ant-spin-nested-loading css-ngmjqf&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[@class=&quot;ant-table&quot;]/div[@class=&quot;ant-table-container&quot;]/div[@class=&quot;ant-table-content&quot;]/table[1]/tbody[@class=&quot;ant-table-tbody&quot;]/tr[@class=&quot;ant-table-row ant-table-row-level-0&quot;]/td[@class=&quot;ant-table-cell ant-table-cell-row-hover&quot;]/div[1]/div[1]/img[@class=&quot;ic_info_teamprofile&quot;]</value>
      <webElementGuid>b382df04-d0a6-43c9-8749-56a41c618696</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@name='icon-info-team-profile-team-monitoring']</value>
      <webElementGuid>f616410f-bee5-4a1b-a195-8586928bcd48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content-main']/div/div/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div/table/tbody/tr/td[3]/div/div/img</value>
      <webElementGuid>427e6ad1-189c-464e-b75f-43cac49d8cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/img</value>
      <webElementGuid>c5716961-d08a-4421-b685-ea980eac36ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@name = 'icon-info-team-profile-team-monitoring' and @src = '/assets/ic_info_teamprofile-88f146be.svg']</value>
      <webElementGuid>fdb23bd6-b050-4569-b627-68f1b9e4962b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
