<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search_Name_Team_Monitoring</name>
   <tag></tag>
   <elementGuidId>432ba32e-0db2-4650-bb41-27b8d396e953</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.ant-input.ant-input-lg.css-ngmjqf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>340230f4-e138-4d2a-a7c9-5cd2fa232c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search Name</value>
      <webElementGuid>6dc26716-3da8-4cf9-868f-b72f19f12a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-lg css-ngmjqf</value>
      <webElementGuid>b6f883ef-1f18-4d15-9594-601fd3ec709b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>208d2732-f96b-45a8-94ea-18cfe7902a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-main&quot;)/div[1]/div[@class=&quot;ant-row h-100 css-1eeazh9&quot;]/div[@class=&quot;ant-col ant-col-24 h-100 css-1eeazh9&quot;]/div[@class=&quot;ant-row css-1eeazh9&quot;]/div[@class=&quot;ant-card ant-card-bordered card-teamlearningstatusdetail-table-teammonitoring css-ngmjqf&quot;]/div[@class=&quot;ant-card-body&quot;]/div[@class=&quot;ant-row css-ngmjqf&quot;]/div[@class=&quot;ant-col ant-col-12 css-ngmjqf&quot;]/span[@class=&quot;ant-input-affix-wrapper ant-input-affix-wrapper-focused search-table ant-input-affix-wrapper-lg css-ngmjqf&quot;]/input[@class=&quot;ant-input ant-input-lg css-ngmjqf&quot;]</value>
      <webElementGuid>1814711a-f4ef-4a20-b24b-9d133a78dd91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>b03e43dc-f349-4e2f-a3c7-957445b9be87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content-main']/div/div/div/div[2]/div/div/div/div/span/input</value>
      <webElementGuid>ceb4c277-169f-4e38-9663-71a063f2b15a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>bcd0ee8b-3472-4d0d-a572-581e72302a87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search Name' and @type = 'text']</value>
      <webElementGuid>7a401c3c-2497-4324-9da6-6702fe90436a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
