<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Member_Notification_Team_Monitoring</name>
   <tag></tag>
   <elementGuidId>e7bbd742-12de-45c4-9841-7c5f5a0493f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;select-member-notification-team-monitoring&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='select-member-notification-team-monitoring']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c074175-75e1-4530-90c8-d27502bdf36b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>select-member-notification-team-monitoring</value>
      <webElementGuid>e3367ec5-ba18-4af2-b1f9-b99b2574ee9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>202ae36b-eaa6-463b-91a5-cb7f0c00b773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-checkbox-input</value>
      <webElementGuid>166a05e2-8669-48a4-b3ff-0d8a190deb40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>80b0e7ae-0a99-408e-8065-adf134d44ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-main&quot;)/div[1]/div[@class=&quot;ant-row h-100 css-1eeazh9&quot;]/div[@class=&quot;ant-col ant-col-24 h-100 css-1eeazh9&quot;]/div[@class=&quot;ant-row css-1eeazh9&quot;]/div[@class=&quot;ant-card ant-card-bordered card-selectedprogram-table-teammonitoring css-1eeazh9&quot;]/div[@class=&quot;ant-card-body&quot;]/div[@class=&quot;ant-row css-1eeazh9&quot;]/div[@class=&quot;ant-col ant-col-24 css-1eeazh9&quot;]/div[@class=&quot;ant-table-wrapper table-selectedprogram-teammonitoring css-1eeazh9&quot;]/div[@class=&quot;ant-spin-nested-loading css-1eeazh9&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[@class=&quot;ant-table&quot;]/div[@class=&quot;ant-table-container&quot;]/div[@class=&quot;ant-table-content&quot;]/table[1]/tbody[@class=&quot;ant-table-tbody&quot;]/tr[@class=&quot;ant-table-row ant-table-row-level-0&quot;]/td[@class=&quot;ant-table-cell ant-table-selection-column&quot;]/label[@class=&quot;ant-checkbox-wrapper css-1eeazh9&quot;]/span[@class=&quot;ant-checkbox ant-wave-target css-1eeazh9&quot;]/input[@class=&quot;ant-checkbox-input&quot;]</value>
      <webElementGuid>63002447-1ee0-4ef9-831e-93ef601e4dad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='select-member-notification-team-monitoring']</value>
      <webElementGuid>3c1a6202-e74b-4d40-a62b-53bc207685e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content-main']/div/div/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div/table/tbody/tr/td/label/span/input</value>
      <webElementGuid>cd07e5df-19e3-40f3-9f8c-8f604bb2a9b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/label/span/input</value>
      <webElementGuid>e6ab8342-113e-4ace-94ba-3304c33605be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'select-member-notification-team-monitoring' and @type = 'checkbox']</value>
      <webElementGuid>702301fa-1ef9-4299-bd10-4217a15cf8df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
