<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_All_Progress_Program_Team_Monitoring</name>
   <tag></tag>
   <elementGuidId>be46462d-a75f-4343-bb2c-11076f2fe655</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c9b9b18b-37fc-4506-9717-6ca61db8ec07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All Progress</value>
      <webElementGuid>ceb049ed-2f6a-499c-89d3-a15cb75f165c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
