<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_Team_Profile_Additional_Learning_Team_Monitoring</name>
   <tag></tag>
   <elementGuidId>3e2eb600-7dda-4d22-a8fe-ce7ed35c5eac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[name=&quot;tab-additional-learning-member-profile-team-monitoring&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@name='tab-additional-learning-member-profile-team-monitoring']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bb3c2644-26c2-42fe-b2d6-523d00b3e391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tab-additional-learning-member-profile-team-monitoring</value>
      <webElementGuid>336d8177-dc0f-4c21-b8d8-c5da9ce25fc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-tooltip-open</value>
      <webElementGuid>22858d09-ea94-45c6-9c94-0b0877b175e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Additional Learning (0)</value>
      <webElementGuid>9da892b0-3194-4404-8cec-177e84ec39de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-tabs-1-tab-4&quot;)/div[@class=&quot;ant-tooltip-open&quot;]</value>
      <webElementGuid>5c308029-5d82-4ce2-8ab3-edff4bd26d75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@name='tab-additional-learning-member-profile-team-monitoring']</value>
      <webElementGuid>459160db-26a3-4972-9b71-e1c208f82383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-tabs-1-tab-4']/div</value>
      <webElementGuid>3aacce50-365d-47b8-be80-5ecde8a8a616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No certificates acquired yet'])[1]/preceding::div[3]</value>
      <webElementGuid>83a8e6ab-0f90-4746-8e83-bb817729a6e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not completed any module yet'])[1]/preceding::div[5]</value>
      <webElementGuid>40ff6f90-df13-4aa9-8e05-84acfc5f28eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Additional Learning']/parent::*</value>
      <webElementGuid>c72a4536-8a9f-403b-8784-7515e8b2ddcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[4]/div/div</value>
      <webElementGuid>117fc462-1e75-4301-8795-bac966de6955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@name = 'tab-additional-learning-member-profile-team-monitoring' and (text() = 'Additional Learning (0)' or . = 'Additional Learning (0)')]</value>
      <webElementGuid>e95f7003-a15c-480a-99f5-d86f6c51e610</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
