<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_Team_Profile_Certificates_Team_Monitoring</name>
   <tag></tag>
   <elementGuidId>e4c20864-df82-4783-87c5-5e536e7994d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[name=&quot;tab-certificate-member-profile-team-monitoring&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@name='tab-certificate-member-profile-team-monitoring']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>904686de-86a0-4954-bc5a-5f91ec233bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tab-certificate-member-profile-team-monitoring</value>
      <webElementGuid>e058ae09-94fb-4b27-85dc-9b4eaf6dc8f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Certificates (0)</value>
      <webElementGuid>28fb4f8b-3acd-4ca1-a762-daeb811e044a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-tabs-1-tab-1&quot;)/div[1]</value>
      <webElementGuid>65194f70-4ca5-4bdb-a282-e8b176df64d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@name='tab-certificate-member-profile-team-monitoring']</value>
      <webElementGuid>8f3f28cb-19a5-4328-9641-d466f3632c07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-tabs-1-tab-1']/div</value>
      <webElementGuid>03fcc943-7bae-41b6-8584-5f4c534e5410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registered on'])[1]/following::div[9]</value>
      <webElementGuid>87783693-fe59-4a05-8c74-827de1bdcf67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='hafizh@digimasia.com'])[1]/following::div[12]</value>
      <webElementGuid>2309f044-3ce2-41e5-9c1c-f4102471532f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Certificates']/parent::*</value>
      <webElementGuid>8cf5d044-8a5c-4140-a9ab-5b5d00f5f3b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div</value>
      <webElementGuid>29783b5f-df85-4e67-8e44-37102d2303c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@name = 'tab-certificate-member-profile-team-monitoring' and (text() = 'Certificates (0)' or . = 'Certificates (0)')]</value>
      <webElementGuid>fde4c3f9-7959-4c19-bb75-ed63364713d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
