<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_Team_Profile_Badges_Team_Monitoring</name>
   <tag></tag>
   <elementGuidId>f43357b7-fdf1-4e7b-baf2-7b91805e4557</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[name=&quot;tab-badges-member-profile-team-monitoring&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@name='tab-badges-member-profile-team-monitoring']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8ee168e9-0fb0-415c-8c79-4446d8aa9060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tab-badges-member-profile-team-monitoring</value>
      <webElementGuid>43246096-02f7-4d65-a58a-853989d57a9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Badges (1)</value>
      <webElementGuid>39a62d2d-e7c4-480d-86eb-b6f7b5f115d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-tabs-1-tab-2&quot;)/div[1]</value>
      <webElementGuid>a30e4193-44ca-4cc2-a68d-df727321480c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@name='tab-badges-member-profile-team-monitoring']</value>
      <webElementGuid>28b1d6b5-2d0f-4291-9188-705671bc3f07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-tabs-1-tab-2']/div</value>
      <webElementGuid>ebb0d3f4-0941-4baf-bded-bac0809798ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registered on'])[1]/following::div[12]</value>
      <webElementGuid>7d0ec8e3-36eb-48e0-b6af-0c77c6fa9aee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Badges']/parent::*</value>
      <webElementGuid>0a613fa8-2176-4e9e-962f-9c4a70d40bad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div/div</value>
      <webElementGuid>af80c5e0-43e5-4b96-bd7c-128fcf523810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@name = 'tab-badges-member-profile-team-monitoring' and (text() = 'Badges (1)' or . = 'Badges (1)')]</value>
      <webElementGuid>ac071c8f-ebf8-4e1c-b73b-070c550bc5b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
