<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_Team_Profile_Completed_Program_Team_Monitoring</name>
   <tag></tag>
   <elementGuidId>36f70a6d-e813-428d-97a0-f6c9b530ae0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[name=&quot;tab-completed-program-member-profile-team-monitoring&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@name='tab-completed-program-member-profile-team-monitoring']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9f856c87-0099-450f-bec0-69e7c0e4b18f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tab-completed-program-member-profile-team-monitoring</value>
      <webElementGuid>2e7bac92-dcd3-4391-aac4-a1ac2263b5c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-tooltip-open</value>
      <webElementGuid>b1d0fa75-6462-49de-a6c8-03525b36663b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Completed Program (2)</value>
      <webElementGuid>404a5fd0-98e1-458d-9000-46b4db29c88f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-tabs-1-tab-3&quot;)/div[@class=&quot;ant-tooltip-open&quot;]</value>
      <webElementGuid>401108ba-668f-46de-b2b4-c86657ff6da3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@name='tab-completed-program-member-profile-team-monitoring']</value>
      <webElementGuid>3a2b2b50-9a3a-47c1-82d3-64f54c3885cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-tabs-1-tab-3']/div</value>
      <webElementGuid>cb223432-fb16-45bf-9f49-8cf68beb5516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No certificates acquired yet'])[1]/preceding::div[6]</value>
      <webElementGuid>334462c2-702b-4764-83b4-3240b9a0240e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Completed Program']/parent::*</value>
      <webElementGuid>a62c14ae-b0bd-4ce9-a8d5-6dd71e300376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[3]/div/div</value>
      <webElementGuid>e1881d2d-5a87-4e64-870f-fbf72b404ab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@name = 'tab-completed-program-member-profile-team-monitoring' and (text() = 'Completed Program (2)' or . = 'Completed Program (2)')]</value>
      <webElementGuid>2c4cb45f-11fc-4127-98ab-f682aac883ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
