<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_Successfully_Open_Team_Monitoring - Button Show All Learning Status</name>
   <tag></tag>
   <elementGuidId>d0c88f40-5cc9-47be-a8bd-a4741fa1f2ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[126]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ant-btn.css-1eeazh9.ant-btn-default.btn-showdetaillearningstatus-teammonitoring</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ddf93ed8-f5ce-4747-bd3c-fd777e70cf8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bece1c52-bb8d-4c84-b819-b506f937646e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn css-1eeazh9 ant-btn-default btn-showdetaillearningstatus-teammonitoring</value>
      <webElementGuid>40dbadb1-89d4-404e-be90-22e2c3390f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Show All</value>
      <webElementGuid>57e326fa-6e08-415f-9c04-be9aa7cec180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-main&quot;)/div[1]/div[@class=&quot;ant-row h-100 css-1eeazh9&quot;]/div[@class=&quot;ant-col ant-col-7 h-100 css-1eeazh9&quot;]/div[@class=&quot;ant-row css-1eeazh9&quot;]/div[@class=&quot;ant-col w-100 h-100 css-1eeazh9&quot;]/div[@class=&quot;ant-card ant-card-bordered css-1eeazh9&quot;]/div[@class=&quot;ant-card-body&quot;]/div[@class=&quot;ant-row css-1eeazh9&quot;]/div[@class=&quot;ant-col ant-col-10 css-1eeazh9&quot;]/a[1]/button[@class=&quot;ant-btn css-1eeazh9 ant-btn-default btn-showdetaillearningstatus-teammonitoring&quot;]</value>
      <webElementGuid>274dd2ba-61c1-498a-9801-e939d3a70ebf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[126]</value>
      <webElementGuid>507ea60f-137d-4b5f-bd06-d6b669172310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content-main']/div/div/div[2]/div[2]/div/div/div/div/div[2]/a/button</value>
      <webElementGuid>a13d055b-afeb-4b77-836f-77acffac4cbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learning Status'])[1]/following::button[1]</value>
      <webElementGuid>063f71ba-afb4-496f-af53-5393cf4f88b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Team Monitoring'])[3]/following::button[1]</value>
      <webElementGuid>5d0fb90d-0f5a-4f68-8011-d526f2f3b557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Candra Prasetio'])[2]/preceding::button[1]</value>
      <webElementGuid>e85081e9-5346-46df-9f01-925c50e2d428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/a/button</value>
      <webElementGuid>6d2c6377-a5ad-4a60-8d7d-ff4a283b3718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Show All' or . = 'Show All')]</value>
      <webElementGuid>53e11b9d-e79c-4013-9654-c85938f48e97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
