<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_view_certificates_user_profile</name>
   <tag></tag>
   <elementGuidId>c5f09643-4755-402f-ac68-73f6449d0eca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'btn-view-certificates-user-profile' and @data-index = '0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-view-certificates-user-profile</value>
      <webElementGuid>9690d8b4-7f0e-42cf-a2ac-23dde6999739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>125d88d1-710a-49ef-95c5-88ac27567d2c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
