<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Card_Module_Review_Reviews</name>
   <tag></tag>
   <elementGuidId>56fce43d-db14-4e7d-8f13-00c56c669723</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@name='card-module-review']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[name=&quot;card-module-review&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>75ffc830-bd44-4904-97f2-513cdb438355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1d617cca-b891-440e-8650-6a1591f3ad84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>module-id</name>
      <type>Main</type>
      <value>223</value>
      <webElementGuid>3d6403c8-aa38-434c-84c0-e80476d85b8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card-module-review</value>
      <webElementGuid>6e076402-38cf-4556-b43d-24a418457ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-module-review active</value>
      <webElementGuid>e196ca09-382e-4840-a73e-df7635fadce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/reviews/module/223/56</value>
      <webElementGuid>75e9051d-830d-4c84-9e9a-fa2119f23537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>435b724a-9948-4297-b8ba-2d27bd1e8721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Office Tour ChallengeProgram: DevelopmentDeadline: -Need Review: 1</value>
      <webElementGuid>3e929640-9252-4d33-b44b-35964c2a4bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-main&quot;)/div[1]/div[@class=&quot;ant-row css-ruwp3i&quot;]/div[@class=&quot;ant-col ant-col-11 css-ruwp3i&quot;]/div[@class=&quot;ant-card ant-card-bordered css-ruwp3i&quot;]/div[@class=&quot;ant-card-body&quot;]/div[1]/a[@class=&quot;card-module-review active&quot;]</value>
      <webElementGuid>e107a216-c539-4018-87c8-bb205c5d321b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@name='card-module-review']</value>
      <webElementGuid>8848679c-3e83-490e-8270-d60d6416de4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content-main']/div/div[2]/div/div/div/div/a</value>
      <webElementGuid>b5be9d33-68b1-4f8d-a139-88c22a979ae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='There are no submissions that need review.'])[1]/following::a[1]</value>
      <webElementGuid>fcb4c835-b330-4f80-a3d9-3a9837d10f31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/reviews/module/223/56')]</value>
      <webElementGuid>a4ee306e-b657-40bd-a4dc-3471d64a91c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/a</value>
      <webElementGuid>2ececebd-e2fd-4e45-8981-82d69cfa7612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@name = 'card-module-review' and @href = '/reviews/module/223/56' and (text() = 'Office Tour ChallengeProgram: DevelopmentDeadline: -Need Review: 1' or . = 'Office Tour ChallengeProgram: DevelopmentDeadline: -Need Review: 1')]</value>
      <webElementGuid>6ab9dbcc-5043-44af-acae-6eeb4d62d660</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
