<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_button_Filter_All_Reviews</name>
   <tag></tag>
   <elementGuidId>b907c848-3e38-42cb-9694-d16063e6b7af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='radio-btn-all-review']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#radio-btn-all-review</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e99474e0-6128-4062-a703-640d42d2e04a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio-btn-all-review</value>
      <webElementGuid>afe225d0-6d19-432e-8322-f4747f1f3718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All (1)</value>
      <webElementGuid>b50e0900-8570-4435-a43a-2672df600f54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio-btn-all-review&quot;)</value>
      <webElementGuid>63a5dcb0-a408-4660-b33d-88f8f2e24ef9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='radio-btn-all-review']</value>
      <webElementGuid>488c0539-76cd-4284-990b-eded9caa49ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content-main']/div/div[2]/div[2]/div/div/div/div/div/label[4]/span[2]/span</value>
      <webElementGuid>6b293e4a-b254-4581-9f6d-dc3d25c037f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(0)'])[2]/following::span[4]</value>
      <webElementGuid>63cda199-3ee5-401d-80ce-9b24832fce56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approved'])[1]/following::span[5]</value>
      <webElementGuid>ffed47d6-336c-4641-aa83-f12004c5c0a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[4]/span[2]/span</value>
      <webElementGuid>d22fd6cf-8e34-43af-be1d-a84c04bcf405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'radio-btn-all-review' and (text() = 'All (1)' or . = 'All (1)')]</value>
      <webElementGuid>9732912a-92b7-4d64-9884-8f0b6ad37b67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
