<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_button_Filter_Approve_Reviews</name>
   <tag></tag>
   <elementGuidId>202d7e22-d686-409b-b8b6-aac173a05eb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='radio-btn-approved-review']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#radio-btn-approved-review</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3f79a1d0-e84a-407a-acb0-d9b03318120d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio-btn-approved-review</value>
      <webElementGuid>0b4cc4bb-697f-4819-8d11-ac9cf8e5d59e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Approved (0)</value>
      <webElementGuid>8da28580-cb5b-40aa-a76f-1ff0872278da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio-btn-approved-review&quot;)</value>
      <webElementGuid>ea38ea3a-1f77-4a34-8d05-ffa0cdd7d63a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='radio-btn-approved-review']</value>
      <webElementGuid>10410fc4-7af8-4547-9977-38360af8041e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content-main']/div/div[2]/div[2]/div/div/div/div/div/label[3]/span[2]/span</value>
      <webElementGuid>37a6c061-5fb2-446f-a2a9-a6ec5155be3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(0)'])[1]/following::span[4]</value>
      <webElementGuid>b2495836-5442-4987-8254-52109b783fbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Declined'])[1]/following::span[5]</value>
      <webElementGuid>96292f32-a82c-40ed-b30a-b875067f6907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[3]/span[2]/span</value>
      <webElementGuid>40c9790d-0370-4e97-9f01-cbe69e0e6a70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'radio-btn-approved-review' and (text() = 'Approved (0)' or . = 'Approved (0)')]</value>
      <webElementGuid>4e3934ac-d3ca-42ba-ad31-49770a868834</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
