<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_button_Filter_Declined_Reviews</name>
   <tag></tag>
   <elementGuidId>99ae99a9-6d05-4ec5-814f-d2eee5701c3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='radio-btn-decline-review']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#radio-btn-decline-review</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>591a97b3-5970-4d7a-afb4-64ee415d9636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio-btn-decline-review</value>
      <webElementGuid>7264397e-6645-4580-8381-facdccb3f22a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Declined (0)</value>
      <webElementGuid>5a5cb67f-715c-4430-8e48-e3ac5d8219ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio-btn-decline-review&quot;)</value>
      <webElementGuid>0601ff7b-7de8-4663-88c0-52d661e0923d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='radio-btn-decline-review']</value>
      <webElementGuid>2f656b12-df54-4657-85bf-303378fa0829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content-main']/div/div[2]/div[2]/div/div/div/div/div/label[2]/span[2]/span</value>
      <webElementGuid>8c88800e-b77b-4543-8001-a44284444c76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(1)'])[1]/following::span[4]</value>
      <webElementGuid>6dc5463a-aeaa-4526-8007-46773be5e881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Need Review'])[4]/following::span[5]</value>
      <webElementGuid>f518f672-36ba-4c64-90a4-7635334df763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/span[2]/span</value>
      <webElementGuid>407ff353-fc7c-498f-8bb6-370aaf2faabf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'radio-btn-decline-review' and (text() = 'Declined (0)' or . = 'Declined (0)')]</value>
      <webElementGuid>c4019c99-821c-4730-96b3-a56cf48fce5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
