<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_Successfully_Open_Reviews - Radio Button Need Review</name>
   <tag></tag>
   <elementGuidId>5b2370a6-f274-4a7b-8e83-05f50b7f9ddb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='radio-btn-need-review-review']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#radio-btn-need-review-review</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c8fbddee-41cc-4069-929a-0542ff126214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio-btn-need-review-review</value>
      <webElementGuid>db305f90-9d7f-4fd1-a201-935f9b32eba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Need Review (1)</value>
      <webElementGuid>09bac8e0-8351-47c3-9a20-bcb1b8372ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio-btn-need-review-review&quot;)</value>
      <webElementGuid>1f19f706-2463-4de9-8381-e9ce1b1c93bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='radio-btn-need-review-review']</value>
      <webElementGuid>2cc9c3d0-cba7-45d1-a8a9-b86b01b6cb70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content-main']/div/div[2]/div[2]/div/div/div/div/div/label/span[2]/span</value>
      <webElementGuid>8dd8d820-0547-4d32-89ac-eecc133a9e9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter'])[1]/following::span[4]</value>
      <webElementGuid>69f3766d-0067-4b80-89c0-b7519c4693bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span</value>
      <webElementGuid>55ec6873-8388-4a47-a9f9-48eaa7bf9af8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'radio-btn-need-review-review' and (text() = 'Need Review (1)' or . = 'Need Review (1)')]</value>
      <webElementGuid>4dcfcbe7-90f7-4f1d-b43f-da6bd257ac3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
