<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_Successfully_Open_Reviews - Text title Review</name>
   <tag></tag>
   <elementGuidId>632bc252-253f-498d-a591-190c85f83d37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='content-main']/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.general-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7f622fa0-386f-4352-bae9-1586859c7566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>general-title</value>
      <webElementGuid>f0434c3e-7926-499e-a302-14c39ec92f36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text-title</name>
      <type>Main</type>
      <value>text-title-review</value>
      <webElementGuid>7a1343ce-db95-44ae-a92d-50c120f6c293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Let's review these learner submissions!</value>
      <webElementGuid>d0ac36b5-7067-4b89-a3f3-91522977a7b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-main&quot;)/div[1]/div[@class=&quot;ant-row ant-row-top css-ruwp3i&quot;]/div[@class=&quot;ant-col ant-col-18 css-ruwp3i&quot;]/div[@class=&quot;general-title&quot;]</value>
      <webElementGuid>bf77897f-2bad-431f-b8fb-231de2405c0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content-main']/div/div/div/div</value>
      <webElementGuid>a941b7fe-5930-45ef-987c-73bf172a9d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help Center'])[1]/following::div[5]</value>
      <webElementGuid>1d19471d-c9c4-4e66-8bd6-953ae6f2ac55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reviews'])[1]/following::div[6]</value>
      <webElementGuid>54b15434-e537-4089-89ee-c2a8cbfdcff6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='There are no submissions that need review.'])[1]/preceding::div[2]</value>
      <webElementGuid>10c8912c-5b15-47c8-b019-560174a083bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coaching Smart Service Delivery'])[1]/preceding::div[5]</value>
      <webElementGuid>c759cdd6-4d86-49d7-92cc-0a51cccb5cab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div/div</value>
      <webElementGuid>534fb510-ed3e-42ef-9a35-3a16988aad7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;Let&quot; , &quot;'&quot; , &quot;s review these learner submissions!&quot;) or . = concat(&quot;Let&quot; , &quot;'&quot; , &quot;s review these learner submissions!&quot;))]</value>
      <webElementGuid>0a5dbc3f-af1c-4de3-b04e-d92f6ef873e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
