<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_Successfully_Open_Reviews - Radio Button Approved</name>
   <tag></tag>
   <elementGuidId>a85b07e2-6cb9-4f99-a841-367e9c63f7a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='radio-btn-approved-review']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#radio-btn-approved-review</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1c02b227-6270-4049-b8e3-84ce970501de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio-btn-approved-review</value>
      <webElementGuid>6af744b1-6e47-430d-b02f-346bbcb3436c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Approved (0)</value>
      <webElementGuid>782291ac-bc35-42ac-b29e-d784c999f820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio-btn-approved-review&quot;)</value>
      <webElementGuid>84800318-c3d0-4363-922a-1ec77048d87a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='radio-btn-approved-review']</value>
      <webElementGuid>cb436ed2-034a-4385-a361-0bf0cd611475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content-main']/div/div[2]/div[2]/div/div/div/div/div/label[3]/span[2]/span</value>
      <webElementGuid>641798a0-4c05-4b3e-b614-5c31cb0e1e41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(0)'])[1]/following::span[4]</value>
      <webElementGuid>c1943df7-79cc-4bbb-a66f-5b900c093c37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Declined'])[1]/following::span[5]</value>
      <webElementGuid>e1297ee5-01ed-4e90-8fc4-364f668b81e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[3]/span[2]/span</value>
      <webElementGuid>186849f2-4f99-4b11-b2bd-e8727ebf75b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'radio-btn-approved-review' and (text() = 'Approved (0)' or . = 'Approved (0)')]</value>
      <webElementGuid>52075c34-1427-4b62-9033-3a3a3d93d84d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
