<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_Successfully_Open_Reviews - Radio Button Declined</name>
   <tag></tag>
   <elementGuidId>1cd2f70e-ce58-42ef-a28e-43aceed2c4ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='radio-btn-decline-review']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#radio-btn-decline-review</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7f899036-9248-4aa3-967b-c4853be39f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio-btn-decline-review</value>
      <webElementGuid>b32d02fe-09ce-4b41-986f-412032c7e0ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Declined (0)</value>
      <webElementGuid>eefc698d-9db6-465a-b33f-070456f7c76e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio-btn-decline-review&quot;)</value>
      <webElementGuid>167404e3-2bfd-42c8-85b6-6710f1adafef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='radio-btn-decline-review']</value>
      <webElementGuid>f8d2300f-fb64-44e4-8595-707213df6793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content-main']/div/div[2]/div[2]/div/div/div/div/div/label[2]/span[2]/span</value>
      <webElementGuid>0c2cadb6-e5df-4ad2-8267-6f818c6d9003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(1)'])[1]/following::span[4]</value>
      <webElementGuid>3289d964-65f3-4cb4-a1c6-9a8ee47d90b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Need Review'])[10]/following::span[5]</value>
      <webElementGuid>4000fcf8-1c53-4d65-9df4-ae91fae0f3b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/span[2]/span</value>
      <webElementGuid>09559774-c561-4fa2-86e5-77b37eb8a476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'radio-btn-decline-review' and (text() = 'Declined (0)' or . = 'Declined (0)')]</value>
      <webElementGuid>fe90831f-06c9-4b2c-b59a-0639680e7bdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
