<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-Modal-Close-Notif-Content-Library</name>
   <tag></tag>
   <elementGuidId>2ba8d01d-6081-486b-a842-9c3740ad51db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='btn-modal-close-notif-content-library']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-modal-close-notif-content-library</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3defed1b-efb6-47a9-a31d-ffd7228a6933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-modal-close-notif-content-library</value>
      <webElementGuid>b2ab205d-dd9c-4907-8a9c-e26b0ec17911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-modal-close-notif-content-library&quot;)</value>
      <webElementGuid>13ffe8a5-dd68-4b31-8aac-dc76f270075c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='btn-modal-close-notif-content-library']</value>
      <webElementGuid>6879a6c7-b13f-4381-bc34-a6eb8599bf2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Content Library'])[3]/following::div[8]</value>
      <webElementGuid>2dcebcc7-7934-4f50-8178-27bfd17bf0d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Learning Journey'])[2]/following::div[14]</value>
      <webElementGuid>bbc27cc5-8420-42c5-b03d-cae06982a044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='content library updates'])[1]/preceding::div[1]</value>
      <webElementGuid>467e0df1-8ab2-41e4-9589-233f1c45ba33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span/div</value>
      <webElementGuid>b14bd242-d6ac-424d-b9eb-da96852c33b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'btn-modal-close-notif-content-library']</value>
      <webElementGuid>33e041a6-b225-4777-bdff-aab5fa8d4deb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
