<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Remove_Module_from_Collection_Content_Library</name>
   <tag></tag>
   <elementGuidId>cc1d4750-500d-4b9f-855f-9975369b481a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='btn-remove-module-collection-content-library']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;btn-remove-module-collection-content-library&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>43a26ac0-c54d-4ce8-b3d4-ab95076c1596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn-remove-module-collection-content-library</value>
      <webElementGuid>d307a0fb-d609-4aed-8607-b51e4a85c19b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7aad6ef8-51f0-44da-bc64-e59ae7c904da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn css-mkw4qa ant-btn-default btn-remove-collection-content-library</value>
      <webElementGuid>04c7f1b6-1d30-43dd-9d37-27ffbe8fa854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Remove from Collection</value>
      <webElementGuid>5d31c16b-134e-4ed3-ae2c-0418ec45a4bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-main&quot;)/div[@class=&quot;ant-layout css-mkw4qa&quot;]/div[@class=&quot;ant-layout ant-layout-has-sider css-mkw4qa&quot;]/main[@class=&quot;ant-layout-content mh-100 css-mkw4qa&quot;]/div[@class=&quot;ant-layout css-mkw4qa&quot;]/main[@class=&quot;ant-layout-content css-mkw4qa&quot;]/div[1]/div[@class=&quot;ant-row css-mkw4qa&quot;]/div[@class=&quot;ant-col ant-col-6 css-mkw4qa&quot;]/div[1]/div[@class=&quot;btn-collection&quot;]/button[@class=&quot;ant-btn css-mkw4qa ant-btn-default btn-remove-collection-content-library&quot;]</value>
      <webElementGuid>0ac0a3f8-b7bb-4914-813e-a9590a54d97e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='btn-remove-module-collection-content-library']</value>
      <webElementGuid>0bf2ae0a-1137-419f-9540-d01f88c5c579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content-main']/div/div/main/div/main/div/div/div[2]/div/div/button</value>
      <webElementGuid>80c5fcb5-ec36-4841-9ccb-96c559826d1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='asd'])[1]/following::button[1]</value>
      <webElementGuid>59913044-ef69-44e1-a25f-30687edfe2e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unlimited'])[1]/following::button[1]</value>
      <webElementGuid>962450bb-3297-40bb-82fe-b95e65fcf430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CL 1'])[1]/preceding::button[1]</value>
      <webElementGuid>6fa54d14-2fcf-4bf8-b491-e241abd9d731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div[2]/div/div/button</value>
      <webElementGuid>fb66031e-ab81-4585-a14e-1adb74bb3a40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'btn-remove-module-collection-content-library' and @type = 'button' and (text() = 'Remove from Collection' or . = 'Remove from Collection')]</value>
      <webElementGuid>c672d525-7cc1-4f4c-a09c-f6c78ee7d4f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
