<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Remove_Course_from_Collection_Content_Library</name>
   <tag></tag>
   <elementGuidId>d42d018f-2a40-4068-a23f-14e869410ce6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='btn-remove-course-collection-content-library']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;btn-remove-course-collection-content-library&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8930e4a8-a834-47f9-8bf0-a386e31eea9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn-remove-course-collection-content-library</value>
      <webElementGuid>5b8810ad-598a-42b8-82a7-35a05facee6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eb02b2c0-991d-4a19-8b05-5d2630d38973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn css-mkw4qa ant-btn-default btn-remove-collection-content-library</value>
      <webElementGuid>c7f7048f-91d5-4841-b5ff-1c5c0e169793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Remove from Collection</value>
      <webElementGuid>53445661-3860-4735-a33f-c0da49ac0070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-main&quot;)/div[@class=&quot;ant-layout css-mkw4qa&quot;]/div[@class=&quot;ant-layout ant-layout-has-sider css-mkw4qa&quot;]/main[@class=&quot;ant-layout-content mh-100 css-mkw4qa&quot;]/div[1]/div[@class=&quot;ant-flex css-mkw4qa ant-flex-align-stretch ant-flex-vertical&quot;]/div[@class=&quot;ant-flex css-mkw4qa&quot;]/div[2]/div[@class=&quot;btn-collection&quot;]/button[@class=&quot;ant-btn css-mkw4qa ant-btn-default btn-remove-collection-content-library&quot;]</value>
      <webElementGuid>a9d5c752-173b-40bf-8ded-0cc29432b5b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='btn-remove-course-collection-content-library']</value>
      <webElementGuid>ae2c3cce-9727-4af0-9ccd-81d8f136333c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content-main']/div/div/main/div/div/div/div[2]/div/button</value>
      <webElementGuid>433496bf-5ccc-4dee-804b-9968ef91c39c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='course cek badge'])[2]/following::button[1]</value>
      <webElementGuid>76a9971d-2632-49fc-9d3e-de2a7381bdf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COURSE'])[1]/following::button[1]</value>
      <webElementGuid>726e4d41-e66d-4536-afd0-e7a90847d91c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='course cek badge'])[3]/preceding::button[1]</value>
      <webElementGuid>d3952f47-fbc7-4fe7-a86e-a1b40147943a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div/div[2]/div/button</value>
      <webElementGuid>fdcf64bb-5128-4e5c-8fe7-00472ca619a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'btn-remove-course-collection-content-library' and @type = 'button' and (text() = 'Remove from Collection' or . = 'Remove from Collection')]</value>
      <webElementGuid>e6d5d2cc-a533-4ac4-b759-9dbe80cc2fa8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
