<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_tab_Collection_Content_Library</name>
   <tag></tag>
   <elementGuidId>9642084f-f81e-4c7e-87a9-2cf84e44209d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'tab-collection-content-library']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-tabs-0-tab-collection']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rc-tabs-0-tab-collection</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tab-collection-content-library</value>
      <webElementGuid>05ab5ba4-355e-4bdd-a758-ab239cade23e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='rc-tabs-0-tab-collection']</value>
      <webElementGuid>1a84d5de-5cd2-4cbf-b0ac-c615f1cfb311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content-main']/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>ae3477de-7a7d-441d-928d-ed64f3c08c55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Content Library'])[2]/following::div[2]</value>
      <webElementGuid>8051d0cb-bbd3-41bc-8435-5b754ccbf5a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help Center'])[1]/following::div[10]</value>
      <webElementGuid>6e817d29-c618-4e32-839d-4192bdc47e38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QC MLW 5.0'])[1]/preceding::div[6]</value>
      <webElementGuid>c9928b70-7cad-41ad-9adc-494aaf9f3ba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter'])[1]/preceding::div[17]</value>
      <webElementGuid>04d3f453-1f7b-459a-bc27-ca68a267b590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Collection']/parent::*</value>
      <webElementGuid>c20f6bc7-a10b-4b5c-9f3a-0c3d4e99f777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>ebdca1f9-d511-49e6-b8fc-08df8c34764e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'rc-tabs-0-tab-collection' and (text() = 'Collection' or . = 'Collection')]</value>
      <webElementGuid>974f7bed-7463-4f78-a3da-92ce0981a77b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
