<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_No_Remove_From_Collection_Content_Libarary</name>
   <tag></tag>
   <elementGuidId>6a383d29-8fa0-4d4a-a7a1-0d9663b32b2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn-cancel-modal</value>
      <webElementGuid>f57fb6c9-9820-4c19-9e19-3771eff0ccda</webElementGuid>
   </webElementProperties>
</WebElementEntity>
