<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Close_Notif_Content_Library</name>
   <tag></tag>
   <elementGuidId>9e3bd9d5-b056-48cf-b40a-96243c25c7cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-modal-close-notif-content-library</value>
      <webElementGuid>3a49c257-f5ef-4fd7-87e9-068b55e67579</webElementGuid>
   </webElementProperties>
</WebElementEntity>
