<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Enter_Cart_List_Program_Content_Library</name>
   <tag></tag>
   <elementGuidId>0072a945-573c-46a0-b0b9-dda747d031e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ant-btn.css-17fzyon.ant-btn-default.ant-btn-block.btn-enter-list-program-academy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>48ebaa2d-e4dd-47c8-9479-a78ff2a84519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn-enter-list-program-academy</value>
      <webElementGuid>3e11b135-2bc3-42f3-9dcc-d4510c6b48c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>d8f22d5c-a37a-4098-b68c-28599c4be7d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content-main']/div/div[3]/div/div/div/div/div/div[2]/div/div[4]/div/a/button</value>
      <webElementGuid>9cc5374e-f273-44c4-b563-2de88666b220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cek badge'])[1]/following::button[1]</value>
      <webElementGuid>11ae4a54-0b49-4ca6-8e25-e1903cb0e546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check badge Program'])[1]/following::button[1]</value>
      <webElementGuid>6a845989-4c18-4a0a-ba10-ac16c1c5706b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Program “Check badge Program” has been added to your Collection.'])[1]/preceding::button[1]</value>
      <webElementGuid>15e5efd6-7b6e-4428-a85d-269db702a4df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/button</value>
      <webElementGuid>12a7cd53-cba7-4a23-ac28-9db24d984279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Enter' or . = 'Enter')]</value>
      <webElementGuid>c987ef3c-ab7f-4992-80da-955c56c05b46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
