<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Add_Module_Collection_Content_Library</name>
   <tag></tag>
   <elementGuidId>62cedebe-4cb1-485a-af6f-ab49cc6f7259</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='btn-add-module-collection-content-library']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;btn-add-module-collection-content-library&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9521de49-d580-4712-8cfd-a30f7fa62f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn-add-module-collection-content-library</value>
      <webElementGuid>df816ed3-986d-4769-ac3b-1cc67684f947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8b2b7b3c-e03f-4b7c-a16b-cb61a4e866eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn css-mkw4qa ant-btn-default btn-add-collection-content-library</value>
      <webElementGuid>0dec4812-d124-47c1-947e-4849330f1b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add to Collection</value>
      <webElementGuid>5012aaad-133a-4696-a105-441529218c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-main&quot;)/div[@class=&quot;ant-layout css-mkw4qa&quot;]/div[@class=&quot;ant-layout ant-layout-has-sider css-mkw4qa&quot;]/main[@class=&quot;ant-layout-content mh-100 css-mkw4qa&quot;]/div[@class=&quot;ant-layout css-mkw4qa&quot;]/main[@class=&quot;ant-layout-content css-mkw4qa&quot;]/div[1]/div[@class=&quot;ant-row css-mkw4qa&quot;]/div[@class=&quot;ant-col ant-col-6 css-mkw4qa&quot;]/div[1]/div[@class=&quot;btn-collection&quot;]/button[@class=&quot;ant-btn css-mkw4qa ant-btn-default btn-add-collection-content-library&quot;]</value>
      <webElementGuid>a91f393d-d387-457f-ab22-562d317bd546</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='btn-add-module-collection-content-library']</value>
      <webElementGuid>7d9da532-f5c3-4245-9087-17635f49c208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content-main']/div/div/main/div/main/div/div/div[2]/div/div/button</value>
      <webElementGuid>531137e1-e673-4633-8eea-cee68981aa4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='asd'])[1]/following::button[1]</value>
      <webElementGuid>c0dae0cd-4dd5-4f14-aafd-c84e7e26aca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unlimited'])[1]/following::button[1]</value>
      <webElementGuid>8c8f3cf8-36a9-4be8-aad5-8a9f20fd8f2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CL 1'])[1]/preceding::button[1]</value>
      <webElementGuid>21562845-c3b7-4e1f-9ce0-76d7850ec336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div[2]/div/div/button</value>
      <webElementGuid>bc380583-b8d5-4bcc-b87d-28f7863bd6c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'btn-add-module-collection-content-library' and @type = 'button' and (text() = 'Add to Collection' or . = 'Add to Collection')]</value>
      <webElementGuid>8c90387b-0f9b-493e-b9d5-d949aa02e708</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
