<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Delete_Cart_Collection_Content_Library</name>
   <tag></tag>
   <elementGuidId>db80d3ef-0334-4df4-b9b9-3ae23cfb1854</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-tabs-0-panel-contentlibrary']/div/div/div/div[5]/div/div/div/div[2]/div/div[4]/div/a/button/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-index = '0' and @name = 'btn-delete-collection']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6f0d470b-b165-4e4a-a90b-c86d3f873aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn-delete-collection</value>
      <webElementGuid>7cb7ce96-5a13-4b9b-b57a-9b8020051375</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-tabs-0-panel-contentlibrary']/div/div/div/div[5]/div/div/div/div[2]/div/div[4]/div/a/button/span</value>
      <webElementGuid>7f82e8b6-7b5f-4081-8136-16dcd91fad64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Content Library Moleawiz Web Tester 3'])[1]/following::span[2]</value>
      <webElementGuid>47f040b3-da74-4c8b-9f37-ffabe290c390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter'])[4]/following::span[2]</value>
      <webElementGuid>54aba1d6-ba20-4a9a-8d73-b355c05bcd3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Content Library Moleawiz Web Tester 2'])[1]/preceding::span[1]</value>
      <webElementGuid>9f200a00-32bf-48c9-bf0c-03568f456f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter'])[6]/preceding::span[2]</value>
      <webElementGuid>7f886473-4778-4509-b19f-35cdd8b7315b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div[2]/div/div[4]/div/a/button/span</value>
      <webElementGuid>ed7eae94-2ae9-4351-bf30-6a4d7acf0c09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Enter' or . = 'Enter')]</value>
      <webElementGuid>85ac9777-1b39-41c1-b6f4-262f157e3422</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
