<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Add_Course_Collection_Content_Library</name>
   <tag></tag>
   <elementGuidId>cfebebbd-cc8a-4014-b58b-a342144609b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='btn-add-course-collection-content-library']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;btn-add-course-collection-content-library&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1f459c18-f6b8-4acd-9505-07878a09c99d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn-add-course-collection-content-library</value>
      <webElementGuid>4e1fabaa-22c3-4561-9375-23d03bcda5be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c0e0af3b-ae3e-44e5-99d4-078b1dba3469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn css-mkw4qa ant-btn-default btn-add-collection-content-library</value>
      <webElementGuid>1a726934-759a-4b05-bb32-938e4087de31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add to Collection</value>
      <webElementGuid>d31a4575-a21d-4ff1-9e28-efe991c75d1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-main&quot;)/div[@class=&quot;ant-layout css-mkw4qa&quot;]/div[@class=&quot;ant-layout ant-layout-has-sider css-mkw4qa&quot;]/main[@class=&quot;ant-layout-content mh-100 css-mkw4qa&quot;]/div[1]/div[@class=&quot;ant-flex css-mkw4qa ant-flex-align-stretch ant-flex-vertical&quot;]/div[@class=&quot;ant-flex css-mkw4qa&quot;]/div[2]/div[@class=&quot;btn-collection&quot;]/button[@class=&quot;ant-btn css-mkw4qa ant-btn-default btn-add-collection-content-library&quot;]</value>
      <webElementGuid>9b7bf4b0-b2a3-4747-9e55-bd9e449cc5bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='btn-add-course-collection-content-library']</value>
      <webElementGuid>981e5e4b-e052-4a63-a62a-bea09fdc3730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content-main']/div/div/main/div/div/div/div[2]/div/button</value>
      <webElementGuid>02554692-674a-4528-b47a-90678a1d0e87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='course cek badge'])[2]/following::button[1]</value>
      <webElementGuid>9aee0261-d897-4c05-a120-79dff277e798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COURSE'])[1]/following::button[1]</value>
      <webElementGuid>a9c1632c-b08a-4eb3-83db-1654edf2a305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='course cek badge'])[3]/preceding::button[1]</value>
      <webElementGuid>048cd2a8-f6e4-4339-a95b-bb457a644a5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div/div[2]/div/button</value>
      <webElementGuid>710a661c-d243-43df-8b1d-5b1a3a638bff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'btn-add-course-collection-content-library' and @type = 'button' and (text() = 'Add to Collection' or . = 'Add to Collection')]</value>
      <webElementGuid>7dcc2162-c46c-404e-9246-08e7276e58b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
