<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Add_Program_Collection_Content_Library</name>
   <tag></tag>
   <elementGuidId>0c7b763a-bc02-4324-bc0e-61b70d548c8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='btn-add-program-collection-content-library']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;btn-add-program-collection-content-library&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9fb4d967-61bd-4373-bc39-70337fbdaf0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn-add-program-collection-content-library</value>
      <webElementGuid>9b6e2e49-4530-4e33-8692-c992feffe8c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e88aa4be-e92b-44ed-a518-072beb882bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn css-mkw4qa ant-btn-default btn-add-collection-content-library</value>
      <webElementGuid>e89c1d98-be03-47bb-95bf-38c234224074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add to Collection</value>
      <webElementGuid>7ab691c9-bdfc-4b8b-803a-4c10972cc0f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-main&quot;)/div[@class=&quot;ant-layout css-mkw4qa&quot;]/div[@class=&quot;ant-layout ant-layout-has-sider css-mkw4qa&quot;]/main[@class=&quot;ant-layout-content mh-100 css-mkw4qa&quot;]/div[1]/div[@class=&quot;ant-flex css-mkw4qa&quot;]/div[@class=&quot;btn-collection&quot;]/button[@class=&quot;ant-btn css-mkw4qa ant-btn-default btn-add-collection-content-library&quot;]</value>
      <webElementGuid>61b53cd5-516f-4714-97c1-cb516ba797bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='btn-add-program-collection-content-library']</value>
      <webElementGuid>066be839-6260-41d1-8741-fa876baac019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content-main']/div/div/main/div/div/div[3]/button</value>
      <webElementGuid>674bf9a3-db1f-44e3-af9f-66496191c120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check badge Program'])[1]/following::button[1]</value>
      <webElementGuid>07bda329-d802-4360-89a0-a2d7ed1630e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='course cek badge'])[1]/following::button[1]</value>
      <webElementGuid>fb75b51b-966c-44cc-a77a-8f250a6174cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cek badge'])[1]/preceding::button[1]</value>
      <webElementGuid>845b0656-d0f4-440c-9c99-ed62a6a16eb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>702d2fdd-da26-47e0-8af2-1e78ff6d3093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'btn-add-program-collection-content-library' and @type = 'button' and (text() = 'Add to Collection' or . = 'Add to Collection')]</value>
      <webElementGuid>82fdf461-4e31-4719-8b9a-a31f787fb942</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
