<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Yes_Remove_From_Collection_Content_Libarary</name>
   <tag></tag>
   <elementGuidId>c4a213ec-4b3d-4083-ad6f-585954715365</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn-yes-modal</value>
      <webElementGuid>070863ae-32da-4e4e-b9e2-1b6aa64ddf30</webElementGuid>
   </webElementProperties>
</WebElementEntity>
