<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>collapse_Title_Course_Content_Library</name>
   <tag></tag>
   <elementGuidId>da29090c-181d-44ad-8a26-c7c8e576a115</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='id-title-course-collapsed']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id-title-course-collapsed</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cfdaf349-5e5a-42fe-aa19-c7e0c2cf3b98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title-course</value>
      <webElementGuid>d3eb5299-2ff3-49e4-927a-c05c503fdea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-title-course-collapsed</value>
      <webElementGuid>fb42e15c-fe65-4334-ac4e-5c0a5ccbfeb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>course cek badge</value>
      <webElementGuid>a401d053-e75a-42c6-8f86-5b024eef006f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-title-course-collapsed&quot;)</value>
      <webElementGuid>cb25a48a-b625-42ef-b7a1-bad01fc1ce90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='id-title-course-collapsed']</value>
      <webElementGuid>568fcbeb-9608-423e-a1dc-ceecedbe176c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dropdown-list-course-program']/div</value>
      <webElementGuid>dfd21591-3875-4ff5-8a6f-a2f9f45f1e4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help Center'])[1]/following::div[14]</value>
      <webElementGuid>8d8b6d24-6dbc-42b9-a624-c07cffaac290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rewards'])[1]/following::div[15]</value>
      <webElementGuid>c982877e-e807-4208-84a3-38ae6f26c4a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check badge Program'])[1]/preceding::div[4]</value>
      <webElementGuid>d45a290b-4421-483b-903c-96e84e137de2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Collection'])[1]/preceding::div[12]</value>
      <webElementGuid>b8b3b85c-9408-4270-a763-7fe160f2420f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='course cek badge']/parent::*</value>
      <webElementGuid>5e87436a-f63c-4898-bcc1-08515153bf07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div</value>
      <webElementGuid>a2d0cd95-daf6-4ecb-8750-f4d912a97d4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'id-title-course-collapsed' and (text() = 'course cek badge' or . = 'course cek badge')]</value>
      <webElementGuid>c30aee4c-50b0-470a-86e1-2ad705917002</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
