<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>list_data_Module_Program_Content_Library</name>
   <tag></tag>
   <elementGuidId>6c7afdd5-b6ea-4729-84d7-f9911bae1b09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fcb29ca6-2232-4cae-9747-3ec14b6e730b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>list-data-module-program</value>
      <webElementGuid>e8a3379c-5044-4593-8961-f940b918552a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
