<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_btn_Filter_Program_Collection_Content_Library</name>
   <tag></tag>
   <elementGuidId>f22bd6fe-38f9-44a6-a78b-59a73ec2b0f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='radio-btn-program-collection-content-library']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#radio-btn-program-collection-content-library</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b94033f7-ae47-4efb-a813-8ba688d6925e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio-btn-program-collection-content-library</value>
      <webElementGuid>7d3b1ab9-9159-4281-b3ee-391f93a03982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Program</value>
      <webElementGuid>c5e5d7ca-6645-4edb-9c97-e8a03ec516cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio-btn-program-collection-content-library&quot;)</value>
      <webElementGuid>482cc5b0-1b23-45af-bcc2-8a7e64dbe290</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='radio-btn-program-collection-content-library']</value>
      <webElementGuid>4b6d0ebd-4ee8-4d91-9333-9d4ca28f85e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content-main']/div/div[2]/div/label[2]/span[2]/span</value>
      <webElementGuid>5aa97794-3159-4197-9a90-e6fd40471ac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/following::span[4]</value>
      <webElementGuid>9e553ec0-c80b-4654-8521-1f64d86c134f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter'])[1]/following::span[8]</value>
      <webElementGuid>1c09cca2-a68d-447c-be7c-dcf32f57267f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Course'])[1]/preceding::span[3]</value>
      <webElementGuid>22ff08f8-e4cf-46bb-9033-73d7d5c07bda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Module'])[1]/preceding::span[7]</value>
      <webElementGuid>e8c1bc17-abee-4ac5-ab5f-6e933f86fbc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/span[2]/span</value>
      <webElementGuid>4de34be8-9a13-48ad-b88f-f2360f0acc79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'radio-btn-program-collection-content-library' and (text() = 'Program' or . = 'Program')]</value>
      <webElementGuid>6594d3a4-ea65-457f-bd58-d4a6cb0dbc00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
