<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_btn_Filter_Module_Collection_Content_Library</name>
   <tag></tag>
   <elementGuidId>74c1c2ef-a986-472f-a4dc-f3788e428807</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='radio-btn-module-collection-content-library']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#radio-btn-module-collection-content-library</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c18fb5ed-d963-4821-ad1c-0df0ead25bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio-btn-module-collection-content-library</value>
      <webElementGuid>1a2ae5ac-ddef-4a9b-9d60-5434146d3dc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Module</value>
      <webElementGuid>a0885a7b-0375-4d58-a5f2-d93c76262a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio-btn-module-collection-content-library&quot;)</value>
      <webElementGuid>53dee717-c0b2-4963-b693-02a736c49e45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='radio-btn-module-collection-content-library']</value>
      <webElementGuid>0108e50e-8ecd-41cf-88e1-fbf0bd66f915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content-main']/div/div[2]/div/label[4]/span[2]/span</value>
      <webElementGuid>8b91a630-ec40-4fd0-9d7b-456e11efc31a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Course'])[1]/following::span[4]</value>
      <webElementGuid>28caf45c-fd6c-47fb-a356-c1281b710db2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Program'])[1]/following::span[8]</value>
      <webElementGuid>d01ce40e-9b82-4b6e-99da-6ea8807915cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Module']/parent::*</value>
      <webElementGuid>324ef4c4-832b-4c59-868e-60ec628679cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[4]/span[2]/span</value>
      <webElementGuid>57b688db-54ed-4e8b-85b6-57a68182890b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'radio-btn-module-collection-content-library' and (text() = 'Module' or . = 'Module')]</value>
      <webElementGuid>ce17a76f-7d89-404f-81db-180887e3551e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
