<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_Succesfully_Add_Program_Collection_Content_Library - Toast Success Add Program Collection</name>
   <tag></tag>
   <elementGuidId>2344d0e8-8a4b-43c3-a504-854a67326bf3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>snackbar-general</value>
      <webElementGuid>b4d3ce43-f0f5-44dc-9aa7-4f082d2ba43f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>show</value>
      <webElementGuid>ad1866c6-ab58-4b54-ad5a-13607fc6e3cf</webElementGuid>
   </webElementProperties>
</WebElementEntity>
