<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_Succesfully_Remove_Module_Collection_Content_Library - Toast Success Remove Module Collection</name>
   <tag></tag>
   <elementGuidId>1ebb4343-6487-4fdc-b4d3-d89c397cc7e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>snackbar-general</value>
      <webElementGuid>a152398d-3dc9-497d-8376-8693add9f584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>show</value>
      <webElementGuid>cdfc3b51-1238-44be-8052-30ceee50dcf2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
