<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>captcha_Num2_Login</name>
   <tag></tag>
   <elementGuidId>220368ba-9731-4d93-bdac-e86073368ead</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-captcha-num2-login</value>
      <webElementGuid>1a55ac10-9713-47f1-b241-3f60fa01d174</webElementGuid>
   </webElementProperties>
</WebElementEntity>
