<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>captcha_Num1_Login</name>
   <tag></tag>
   <elementGuidId>122f48e5-7be9-4f56-8586-9154c5038dc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-captcha-num1-login</value>
      <webElementGuid>b4ac4d22-50ea-40cd-9d6d-a9eb83e1d8c5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
