<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_Login</name>
   <tag></tag>
   <elementGuidId>4f58b1c7-1dcc-4558-ae25-d51d085373a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-username-login</value>
      <webElementGuid>3da23f0e-2155-4454-88b2-419d3023f522</webElementGuid>
   </webElementProperties>
</WebElementEntity>
