<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Captcha_Your_Answer_Login</name>
   <tag></tag>
   <elementGuidId>42376f33-e56a-460d-9a27-50ad5acb0fe3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-captcha-your-answer-login</value>
      <webElementGuid>d2d382f8-0a88-4229-a3a8-736641936964</webElementGuid>
   </webElementProperties>
</WebElementEntity>
