<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Cart_Redeem_Rewards</name>
   <tag></tag>
   <elementGuidId>413bd892-18ab-43c7-8933-2a867a1d69b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='btn-redeem-rewards']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;btn-redeem-rewards&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>21439152-e6ce-4dcf-8d13-4ebb8268683f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn-redeem-rewards</value>
      <webElementGuid>20a9a0ce-5f08-406d-a74d-636617be32c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>215d81c9-6f0b-4276-bd5e-1690cfc43398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cf34777f-b728-47ff-aaf2-803014b801b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn css-1dq8hl5 ant-btn-default ant-btn-block btn-redeem-rewards</value>
      <webElementGuid>e5e75402-5a25-4c87-88d6-f4115ae428f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Redeem</value>
      <webElementGuid>72845a03-c270-4ad5-8f00-c73a0e2fca79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-main&quot;)/div[1]/div[@class=&quot;ant-row flex-reward-list css-1dq8hl5&quot;]/div[@class=&quot;h-100 w-100 ant-flex css-1dq8hl5 ant-flex-wrap-wrap ant-flex-gap-middle&quot;]/div[@class=&quot;ant-card css-1dq8hl5&quot;]/div[@class=&quot;ant-card-body&quot;]/div[@class=&quot;footer-product&quot;]/div[3]/button[@class=&quot;ant-btn css-1dq8hl5 ant-btn-default ant-btn-block btn-redeem-rewards&quot;]</value>
      <webElementGuid>1517fd4f-692a-4e86-86c5-f439694f8619</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='btn-redeem-rewards']</value>
      <webElementGuid>5d6316ea-1e8e-482e-be54-9630426b6c50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content-main']/div/div[2]/div/div/div/div[2]/div[3]/button</value>
      <webElementGuid>efb3e557-7279-4032-b233-1d5e3e4b4291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reward hafis'])[1]/following::button[1]</value>
      <webElementGuid>d5d8b5b3-11a2-4169-97dc-b9ca35fc0571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Redeem History'])[1]/following::button[1]</value>
      <webElementGuid>bfebf68c-289c-4632-bfbb-dec6b4e27e65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>0071ee50-162c-457d-979d-e5b32859a522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'btn-redeem-rewards' and @type = 'button' and (text() = 'Redeem' or . = 'Redeem')]</value>
      <webElementGuid>9e6da6ce-ecb7-4a93-9328-acaae153fc7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
