<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_History_Earn_Rewards</name>
   <tag></tag>
   <elementGuidId>b12b7a1b-141f-4c0b-b9ea-d79f45a517f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='btn-history-modal-earn-rewards']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;btn-history-modal-earn-rewards&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2da837ad-ff54-463c-8b2b-a04e09338caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn-history-modal-earn-rewards</value>
      <webElementGuid>dec79785-dba3-4006-8c09-89e39e40db31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a8244060-eae4-4181-910a-9a0c0e44ce30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn css-trse47 ant-btn-default ant-btn-block btn-history-modal-earn-rewards</value>
      <webElementGuid>afccaa7d-f69d-4083-8163-275e95285aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>History</value>
      <webElementGuid>763b62be-076c-495c-8566-c97502856192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;main-body light-mode ltr app sidebar-mini&quot;]/div[5]/div[@class=&quot;ant-modal-root css-trse47&quot;]/div[@class=&quot;ant-modal-wrap ant-modal-centered&quot;]/div[@class=&quot;ant-modal css-trse47&quot;]/div[@class=&quot;ant-modal-content&quot;]/div[@class=&quot;ant-modal-body&quot;]/div[@class=&quot;body-modal-earn-rewards&quot;]/div[3]/div[3]/button[@class=&quot;ant-btn css-trse47 ant-btn-default ant-btn-block btn-history-modal-earn-rewards&quot;]</value>
      <webElementGuid>1b100cea-2a20-4f48-8a43-7d859c9f10f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='btn-history-modal-earn-rewards']</value>
      <webElementGuid>d1d8094b-c699-47ad-b8b3-472a3f7bca2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DREW67BZ'])[1]/following::button[1]</value>
      <webElementGuid>37c14274-4a32-4747-b5f2-b06147bf3c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please save this code to claim your reward'])[1]/following::button[1]</value>
      <webElementGuid>8df41715-8a3a-43d2-a643-558b5e6f2901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::button[1]</value>
      <webElementGuid>b949b92f-a809-4053-9a37-6103870ca65e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/button</value>
      <webElementGuid>e64779e5-5064-4579-b325-21b2e44f090f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'btn-history-modal-earn-rewards' and @type = 'button' and (text() = 'History' or . = 'History')]</value>
      <webElementGuid>7cc39fab-7e8c-440b-8de0-a53dee58b288</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
