<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Redeem_Detail_Rewards</name>
   <tag></tag>
   <elementGuidId>d9015d9e-cee8-4c6d-ba82-864b5a8920d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='btn-redeem-detail-rewards']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;btn-redeem-detail-rewards&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0551ffae-402e-4129-a35f-a6e40af2e051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn-redeem-detail-rewards</value>
      <webElementGuid>bdac6293-269f-47f2-886b-bb57cb1433f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1d593851-f426-41a0-a80a-7a81a67ecdcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn css-1dq8hl5 ant-btn-default ant-btn-block btn-redeem-detail-rewards</value>
      <webElementGuid>b56f61e4-2875-4331-b898-b5e999bdc9b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Redeem</value>
      <webElementGuid>e1152189-d051-4d15-bc6e-91c5e8fbd218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;main-body light-mode ltr app sidebar-mini&quot;]/div[3]/div[@class=&quot;ant-modal-root css-1dq8hl5&quot;]/div[@class=&quot;ant-modal-wrap ant-modal-centered&quot;]/div[@class=&quot;ant-modal css-1dq8hl5 modal-detail-rewards&quot;]/div[@class=&quot;ant-modal-content&quot;]/div[@class=&quot;ant-modal-body&quot;]/div[@class=&quot;ant-row css-1dq8hl5&quot;]/div[@class=&quot;ant-col css-1dq8hl5&quot;]/div[5]/button[@class=&quot;ant-btn css-1dq8hl5 ant-btn-default ant-btn-block btn-redeem-detail-rewards&quot;]</value>
      <webElementGuid>2d2f9a05-7a26-445c-bf3e-bdbd4ac2840d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='btn-redeem-detail-rewards']</value>
      <webElementGuid>af34ed3c-2e8d-4ee2-87f7-371dcd7d6a0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>be6232a6-09b1-4bb2-99ba-7bcb1aa223b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not Enough Points'])[1]/following::button[2]</value>
      <webElementGuid>e391184e-484a-4be6-bce7-98dfff479e68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/button[2]</value>
      <webElementGuid>8f911a6e-b3ca-4dac-a673-6b5c47a929f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'btn-redeem-detail-rewards' and @type = 'button' and (text() = 'Redeem' or . = 'Redeem')]</value>
      <webElementGuid>a8dc9b45-d884-4a89-b82b-94f1e2255e40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
