<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Close_Earn_Rewards</name>
   <tag></tag>
   <elementGuidId>2121a520-a29b-4137-9155-627702e6b435</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='btn-close-modal-earn-rewards']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;btn-close-modal-earn-rewards&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7f324bfe-eeb4-4b85-84d4-531a686c19a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn-close-modal-earn-rewards</value>
      <webElementGuid>3f7fcbc1-c9be-4925-bad9-5ae4fe498ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cde431a5-7826-47b7-a0de-4839e5cff541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn css-trse47 ant-btn-default ant-btn-block btn-close-modal-earn-rewards</value>
      <webElementGuid>47df3a8e-bc79-4c5b-937e-6c65d8525c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>3839b925-aaef-4933-b0bc-f1ea33ca8fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;main-body light-mode ltr app sidebar-mini&quot;]/div[5]/div[@class=&quot;ant-modal-root css-trse47&quot;]/div[@class=&quot;ant-modal-wrap ant-modal-centered&quot;]/div[@class=&quot;ant-modal css-trse47&quot;]/div[@class=&quot;ant-modal-content&quot;]/div[@class=&quot;ant-modal-body&quot;]/div[@class=&quot;body-modal-earn-rewards&quot;]/div[3]/div[3]/button[@class=&quot;ant-btn css-trse47 ant-btn-default ant-btn-block btn-close-modal-earn-rewards&quot;]</value>
      <webElementGuid>c6980c5a-2dfd-4b27-ae3c-715f9eff1a43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='btn-close-modal-earn-rewards']</value>
      <webElementGuid>3dec4ca8-1d3a-42fe-8222-c674f46193c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='History'])[1]/following::button[1]</value>
      <webElementGuid>38b2f11a-c71b-4095-beba-d21fbade237c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DREW67BZ'])[1]/following::button[2]</value>
      <webElementGuid>7e76b014-d71c-4933-8500-ba3d46eae8a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button[2]</value>
      <webElementGuid>4cab857d-55d0-48fa-befc-60cddc676253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'btn-close-modal-earn-rewards' and @type = 'button' and (text() = 'Close' or . = 'Close')]</value>
      <webElementGuid>92eed69c-214e-4fdf-a68d-019736a92816</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
