<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Verify_OTP_Rewards</name>
   <tag></tag>
   <elementGuidId>3af773ff-8a3c-4018-bba3-83cc5f3d6a5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='btn-verify-reward']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;btn-verify-reward&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fb086266-d7bf-4ede-a022-5780eecbe4f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9691f3ce-6357-486d-ad8e-af9170a7e45e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn-verify-reward</value>
      <webElementGuid>76bb21e9-4470-4110-83fe-d7f16b4bebc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>827995f4-8c7b-4ba1-8796-22db9d8a9214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn css-11f0w9d ant-btn-default btn btn-sm btn-primary btn-block</value>
      <webElementGuid>94932976-492c-42eb-8df9-3cf05430f636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verify</value>
      <webElementGuid>dd209449-b045-4b11-869a-ce273af2454d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;main-body light-mode ltr app sidebar-mini&quot;]/div[4]/div[@class=&quot;ant-modal-root css-11f0w9d&quot;]/div[@class=&quot;ant-modal-wrap ant-modal-centered&quot;]/div[@class=&quot;ant-modal css-11f0w9d modal-otp-verification&quot;]/div[@class=&quot;ant-modal-content&quot;]/div[@class=&quot;ant-modal-body&quot;]/div[1]/div[@class=&quot;ant-card ant-card-bordered css-11f0w9d&quot;]/div[@class=&quot;ant-card-body&quot;]/form[@class=&quot;ant-form ant-form-horizontal css-11f0w9d&quot;]/div[@class=&quot;ant-row css-11f0w9d&quot;]/div[@class=&quot;ant-col ant-col-24 css-11f0w9d&quot;]/button[@class=&quot;ant-btn css-11f0w9d ant-btn-default btn btn-sm btn-primary btn-block&quot;]</value>
      <webElementGuid>38cf8553-a181-46af-84ae-a731e3ac92a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='btn-verify-reward']</value>
      <webElementGuid>cf49d7be-4e4f-4d80-8376-4ff0bc3f983b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verify Your Account'])[1]/following::button[1]</value>
      <webElementGuid>aeffc7a7-1ea4-411c-8b75-e5d446e72bfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[2]</value>
      <webElementGuid>5d2a9683-5401-489a-8f35-2337387cfd7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/preceding::button[1]</value>
      <webElementGuid>ef76b92b-1b4b-446d-9ca5-a4010a214745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/button</value>
      <webElementGuid>d14bbcec-851a-40bf-b91a-0ee2aa4d13da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'btn-verify-reward' and @type = 'submit' and (text() = 'Verify' or . = 'Verify')]</value>
      <webElementGuid>47ce11cb-230b-47e6-af40-4bcc7b71b1d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
