<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Back_OTP_Rewards</name>
   <tag></tag>
   <elementGuidId>7fd07eb8-fd40-4004-8c66-62edb0a47f7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@name='btn-back-otp-reward']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div[name=&quot;btn-back-otp-reward&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>13104624-62b6-4cbd-8c45-7f7f2d4ad5da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn-back-otp-reward</value>
      <webElementGuid>14971756-f396-4498-bd20-77952c5f8f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-link box-shadow-0</value>
      <webElementGuid>215bfbe9-f216-4616-bbb8-e2e843962385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Back</value>
      <webElementGuid>abf320e5-a735-472d-a73b-a92741066c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;main-body light-mode ltr app sidebar-mini&quot;]/div[4]/div[@class=&quot;ant-modal-root css-11f0w9d&quot;]/div[@class=&quot;ant-modal-wrap ant-modal-centered&quot;]/div[@class=&quot;ant-modal css-11f0w9d modal-otp-verification&quot;]/div[@class=&quot;ant-modal-content&quot;]/div[@class=&quot;ant-modal-body&quot;]/div[1]/div[@class=&quot;ant-card ant-card-bordered css-11f0w9d&quot;]/div[@class=&quot;ant-card-body&quot;]/form[@class=&quot;ant-form ant-form-horizontal css-11f0w9d&quot;]/div[@class=&quot;ant-row css-11f0w9d&quot;]/div[@class=&quot;ant-col ant-col-24 css-11f0w9d&quot;]/div[@class=&quot;btn-link box-shadow-0&quot;]</value>
      <webElementGuid>25271f1a-d9c6-4aeb-b7a7-11d2a2050e06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@name='btn-back-otp-reward']</value>
      <webElementGuid>c17119a4-9b88-469f-810c-0efc920375b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verify'])[1]/following::div[2]</value>
      <webElementGuid>7624bfee-437b-417e-8b29-4bbfa24e538b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verify Your Account'])[1]/following::div[12]</value>
      <webElementGuid>75ac2314-fd60-4afb-8465-b443ae171078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Back']/parent::*</value>
      <webElementGuid>99d42b87-ad87-458d-a1a6-af845e7607ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div[2]/div</value>
      <webElementGuid>8b8527f0-2436-43b4-adb8-f6c808888465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@name = 'btn-back-otp-reward' and (text() = 'Back' or . = 'Back')]</value>
      <webElementGuid>ebf7462f-68c9-49a8-bcab-d36bda3e557d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
