<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancel_Redeem_Detail_Rewards</name>
   <tag></tag>
   <elementGuidId>b1658955-379b-4301-8348-83554e81c73d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='btn-cancel-rewards']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;btn-cancel-rewards&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>26def7e6-7fef-492a-a2df-51713810b9e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn-cancel-rewards</value>
      <webElementGuid>526591e7-07cd-4f2c-a6c9-a4816ca3fd97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ac0e8b68-22a8-419b-bf30-26eea76859ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn css-1dq8hl5 ant-btn-default ant-btn-block btn-cancel-detail-rewards</value>
      <webElementGuid>d2b0aab3-2e1d-4785-b480-1fc1f7cee4db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>76ad22f7-96fd-4d9b-9387-367920fb687f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;main-body light-mode ltr app sidebar-mini&quot;]/div[3]/div[@class=&quot;ant-modal-root css-1dq8hl5&quot;]/div[@class=&quot;ant-modal-wrap ant-modal-centered&quot;]/div[@class=&quot;ant-modal css-1dq8hl5 modal-detail-rewards&quot;]/div[@class=&quot;ant-modal-content&quot;]/div[@class=&quot;ant-modal-body&quot;]/div[@class=&quot;ant-row css-1dq8hl5&quot;]/div[@class=&quot;ant-col css-1dq8hl5&quot;]/div[5]/button[@class=&quot;ant-btn css-1dq8hl5 ant-btn-default ant-btn-block btn-cancel-detail-rewards&quot;]</value>
      <webElementGuid>3ba23aba-ca4e-4a60-9602-5fc2e144a36f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='btn-cancel-rewards']</value>
      <webElementGuid>2fc28261-43bc-4b4b-9ae2-beddc7e67dad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not Enough Points'])[1]/following::button[1]</value>
      <webElementGuid>aa45004d-8790-41b0-a1f6-873a91da23b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Balance'])[1]/following::button[1]</value>
      <webElementGuid>9f269e00-7353-4d6b-ab74-606819ea719a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Redeem'])[2]/preceding::button[1]</value>
      <webElementGuid>7d456e20-9313-4798-8713-dc1854ba41ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/button</value>
      <webElementGuid>fd4dd9f1-10f3-4db8-ac45-73ee316ab7ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'btn-cancel-rewards' and @type = 'button' and (text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>d4d2765b-ec27-4aca-a9cf-c2634a960c80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
