<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Verify Your Account_Verification_Code_Rewards</name>
   <tag></tag>
   <elementGuidId>3d9b47ee-c8a8-4073-94de-99db9fba0283</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id-verification-code-reward']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id-verification-code-reward</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>39b1ba26-ce5a-440a-84a7-93900d42914e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d9fdda5b-68a9-4158-b2d0-29efba7b9a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>bba5ee29-18b3-410c-9675-cb738e242a38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-verification-code-reward</value>
      <webElementGuid>f689d180-f78e-420a-9b24-476d615127d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Verification Code</value>
      <webElementGuid>04e81d10-3867-4a49-bc33-69876ddc3ca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>verification_code</value>
      <webElementGuid>1629fd06-f716-4b6a-92cc-db47d1016264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input css-11f0w9d form-control</value>
      <webElementGuid>4ed0cda0-58ef-4ce2-9361-67ec48200999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-verification-code-reward&quot;)</value>
      <webElementGuid>06618984-a41b-4fa4-b675-951a24d15a1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id-verification-code-reward']</value>
      <webElementGuid>6e750f7d-0356-4305-9860-1c0bc51078b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>0db3e517-3590-4f67-b7a8-67ffcd62d96e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'id-verification-code-reward' and @placeholder = 'Verification Code' and @name = 'verification_code']</value>
      <webElementGuid>a3695450-f58c-439c-bf96-1a5d03df334a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
