<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_Successfully_Open_Rewards - Button Link Redeem History</name>
   <tag></tag>
   <elementGuidId>948faa05-92dd-4756-b546-3a348064d5ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@name='btn-redeem-history-rewards']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[name=&quot;btn-redeem-history-rewards&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7a74ef02-97f0-4aa7-b17e-da2639312d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>redeem-rewards</value>
      <webElementGuid>8ad2eff9-e71c-4206-a69f-5784c91ec0bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn-redeem-history-rewards</value>
      <webElementGuid>5140d4c6-3968-4d69-9eb0-6f5f505c5fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/rewards/history</value>
      <webElementGuid>ccf3bdf3-d704-400a-9a92-838911b6dcd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Redeem History</value>
      <webElementGuid>de02e8ff-e61c-47f8-9886-979cb2191cfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-main&quot;)/div[1]/div[@class=&quot;ant-row ant-row-top row-header-rewards css-1dq8hl5&quot;]/div[@class=&quot;ant-col ant-col-12 css-1dq8hl5&quot;]/a[@class=&quot;redeem-rewards&quot;]</value>
      <webElementGuid>1d564eff-c71d-49d6-9ad3-219dea9d3b45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@name='btn-redeem-history-rewards']</value>
      <webElementGuid>2ddb4ad3-04ca-49ff-ad19-c20cdf8eda40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content-main']/div/div/div[2]/a</value>
      <webElementGuid>480b9611-3f64-448c-ba34-4cf485e5784f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current Balance'])[1]/following::a[1]</value>
      <webElementGuid>5bec6dfe-f5db-474f-bf73-4b99c2b13156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Here exciting rewards for you!'])[1]/following::a[1]</value>
      <webElementGuid>ad465485-cbb8-4e61-88d9-b09987520be4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobil Tesla'])[1]/preceding::a[1]</value>
      <webElementGuid>5a6b3187-69bc-4cf8-96bc-2aa9f3866778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/rewards/history')]</value>
      <webElementGuid>886ed47a-7540-4eeb-a00c-f4da454a560a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>73e39757-01e8-4810-b266-3d33368fc76a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@name = 'btn-redeem-history-rewards' and @href = '/rewards/history' and (text() = 'Redeem History' or . = 'Redeem History')]</value>
      <webElementGuid>d499c6f9-4ec3-45bb-9a6e-5d82b9147fef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
