<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_Successfully_Redeem_Rewards - List Data Histroy Redeem</name>
   <tag></tag>
   <elementGuidId>765a20b8-ecfa-4a39-8465-97828d03e77e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4cb5f1c5-eb86-488a-81d8-18b50e0e36b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>code-redeem-0</value>
      <webElementGuid>ccad3d8e-8b44-4081-8e25-575e67e44b09</webElementGuid>
   </webElementProperties>
</WebElementEntity>
