<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>scroll_list_data_index_0_Ongoing_Program_Home</name>
   <tag></tag>
   <elementGuidId>b1677933-33c1-442c-83af-6740965fb177</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'list-data-ongoing-program-home' and @data-id = '0']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>list-data-ongoing-program-home</value>
      <webElementGuid>75d1db1e-1368-4236-9f61-6706fa0daa6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>601425dc-fd0c-4498-9d76-670c6a9b1591</webElementGuid>
   </webElementProperties>
</WebElementEntity>
